= Práctica #4: Concurrent Futures en Python
:encoding: utf-8
:author: Rubén Escalante Chan (A01370880), Guillermo Pérez Trueba (A01377162)
:email: A01370880@itesm.mx, A01377162@itesm.mx
:revdate: 10 de marzo, 2019.
:toc:
:numbered:
:source-highlighter: pygments
:icons: font
:pygments-style: manni
:toc-title: Tabla de contenido
:last-update-label: Última actualización:
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo
:caution-caption: Precaución
:important-caption: Importante
:note-caption: Nota
:tip-caption: Consejo
:warning-caption: Advertencia
:appendix-caption: Apéndice

Este reporte fue elaborado para el curso de _Programación multinúcleo_ del Tecnológico de Monterrey, Campus Estado de México.

:numbered:

== Introducción

La práctica consta de estimar el logaritmos base _e_ de 2 usando Python. Ésto se debe lograr tanto
de manera secuencial como de manera paralela.

Para calcular un valor aproximado de loge(2) se utiliza la siguiente serie:

****
loge(2) ≈ &#931;(1, n) = (−1)^(i+1)/i ≈ 1−1/2+1/3−1/4+1/5−1/6+⋯+(−1)^(n+1/)n ≈ 0.693147181
****


[NOTE]
.Hardware y software utilizado
====
Los programas se probaron en una computadora de escritorio con las siguientes características:

- Procesador Intel Core i7-6700 de 2.60GHz con cuatro núcleos y ocho _hyperthreads_.
- 16 GiB de memoria RAM.
- Sistema operativo Ubuntu 16.04, kernel de Linux 3.13.0-107 de 64 bits.
- Python 3.6.5.
====

== Solución
La solución consiste en computar la sumatoria de ((-1) ** (i + 1)) / i dónde _i_ va desde 1
hasta _n_. El valor de _n_ es 5_000_000.

.loge2.py
[source,python]
----
include::loge2.py[]
----

El programa produce esta salida:

[source,text]

----

T1=2.2647, Result=0.6931470805600676
T8=1.3367, Result=0.6931470805600217
S8=1.6942
----

== Resultado
A continuación se muestran los tiempos de ejecución de varias corridas de los dos programas:

.Tiempos de ejecución del ordenamiento secuencial
[options="header,footer", cols="^,^", width="70%"]
|====
| # de corrida     | Tiempo T~1~ (segundos)
| 1                | 2.2262
| 2                | 2.2175
| 3                | 4.4203
| 4                | 4.3790
| 5                | 4.3783
| Media aritmética | 3.5242
|====

.Tiempos de ejecución del ordenamiento paralelo
[options="header,footer", cols="^,^", width="70%"]
|====
| # de corrida     | Tiempo T~8~ (segundos)
| 1                | T8=1.1130
| 2                | T8=1.4578
| 3                | T8=1.6161
| 4                | T8=1.7201
| 5                | T8=1.8648
| Media aritmética | T8=1.5544
|====

A partir de las medias aritméticas calculadas, el _speedup_ obtenido en un CPU es:

****
S~8~ = T~1~ / T~8~ = 3.5242 / 1.5544 = 2.2789
****

El _speedup_ obtenido es bastante bueno, siendo mayor a 2. Se podría concluir que el uso de _concurrent.futures_ en python nos ayudará a crear código en paralelo eficiente, sin embargo, esto no resultaría
del todo correcto, ya que en esta misma práctica, y un _N_ = 200 se obtubieron los siguientes resultados:

****
T~1~=0.0001, Result=0.6906534304818243 +
T~8~=0.0479, Result=0.6906534304818243 +
S~8~ = T~1~ / T~8~ = 0.0001 / 0.0479 = 0.0013 +
****

Con estos resultados, se puede concluir que la librería _concurrent.futures_ si nos ayuda a crear algoritmos paralelos eficientes siempre y cuando se tenga un _N_ bastante grande.

== Agradecimientos
Se agradece al profesor Ariel Ortiz por sus enseñanzas y ayuda para solucionar este problema.

== Referencias
[bibliography]

- Ariel Ortiz. (2019). Práctica #4: Concurrent Futures en Python Sitio web: http://34.212.143.74/apps/s201911/tc3039/practica_python_concurrent_futures/
